/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "nmxCentaurScalars.h"


int nmxCentaurSohInteger = 1;
int nmxCentaurSohSleeper = 2;
char nmxCentaurSohString[] = "test";
/** Initializes the nmxCentaurScalars module */
void
init_nmxCentaurScalars(void)
{
    const oid       nmxCentaurSohInteger_oid[] =
        { 1, 3, 6, 1, 4, 1, 58765, 1, 1, 1 };
    const oid       nmxCentaurSohSleeper_oid[] =
        { 1, 3, 6, 1, 4, 1, 58765, 1, 1, 2 };
    const oid       nmxCentaurSohString_oid[] =
        { 1, 3, 6, 1, 4, 1, 58765, 1, 1, 3 };

    DEBUGMSGTL(("nmxCentaurScalars", "Initializing\n"));

    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("nmxCentaurSohInteger",
                             handle_nmxCentaurSohInteger,
                             nmxCentaurSohInteger_oid,
                             OID_LENGTH(nmxCentaurSohInteger_oid),
                             HANDLER_CAN_RWRITE));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("nmxCentaurSohSleeper",
                             handle_nmxCentaurSohSleeper,
                             nmxCentaurSohSleeper_oid,
                             OID_LENGTH(nmxCentaurSohSleeper_oid),
                             HANDLER_CAN_RWRITE));
    netsnmp_register_scalar(netsnmp_create_handler_registration
                            ("nmxCentaurSohString",
                             handle_nmxCentaurSohString,
                             nmxCentaurSohString_oid,
                             OID_LENGTH(nmxCentaurSohString_oid),
                             HANDLER_CAN_RWRITE));
}

int
handle_nmxCentaurSohInteger(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *reqinfo,
                            netsnmp_request_info *requests)
{
    int             ret;
    int*            origin_value = NULL;
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 /*
                                  * XXX: a pointer to the scalar's data 
                                  */ &nmxCentaurSohInteger,
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ sizeof(nmxCentaurSohInteger));
        break;

    /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
    case MODE_SET_RESERVE1:
        /*
         * or you could use netsnmp_check_vb_type_and_size instead 
         */
        ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
        if (ret != SNMP_ERR_NOERROR) {
            netsnmp_set_request_error(reqinfo, requests, ret);
        }
        break;

    case MODE_SET_RESERVE2:
        /*
         * XXX malloc "undo" storage buffer 
         */
        origin_value = netsnmp_memdup(&nmxCentaurSohInteger, sizeof(nmxCentaurSohInteger));
        if ( origin_value == NULL) {
            netsnmp_set_request_error(reqinfo, requests,
                                      SNMP_ERR_RESOURCEUNAVAILABLE);
        }
        break;

    case MODE_SET_FREE:
        /*
         * XXX: free resources allocated in RESERVE1 and/or
         * RESERVE2.  Something failed somewhere, and the states
         * below won't be called. 
         */
        free(origin_value);
        break;

    case MODE_SET_ACTION:
        /*
         * XXX: perform the value change here 
         */
        nmxCentaurSohInteger = *(requests->requestvb->val.integer);
        
        break;

    case MODE_SET_COMMIT:
        /*
         * XXX: delete temporary storage 
         */
        free(origin_value);
        break;

    case MODE_SET_UNDO:
        /*
         * XXX: UNDO and return to previous value for the object 
         */
        nmxCentaurSohInteger = *origin_value;
        
        break;

    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_nmxCentaurSohInteger\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_nmxCentaurSohSleeper(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *reqinfo,
                             netsnmp_request_info *requests)
{
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 /*
                                  * XXX: a pointer to the scalar's data 
                                  */ &nmxCentaurSohSleeper,
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ sizeof(nmxCentaurSohSleeper));
        break;

      
    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_nmxCentaurSohSleeper\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int
handle_nmxCentaurSohString(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *reqinfo,
                            netsnmp_request_info *requests)
{
    /*
     * We are never called for a GETNEXT if it's registered as a
     * "instance", as it's "magically" handled for us.  
     */

    /*
     * a instance handler also only hands us one request at a time, so
     * we don't need to loop over a list of requests; we'll only get one. 
     */

    switch (reqinfo->mode) {

    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                 /*
                                  * XXX: a pointer to the scalar's data 
                                  */&nmxCentaurSohString,
                                 /*
                                  * XXX: the length of the data in bytes 
                                  */ sizeof(nmxCentaurSohString));
        break;

        

    default:
        /*
         * we should never get here, so this is a really bad error 
         */
        snmp_log(LOG_ERR,
                 "unknown mode (%d) in handle_nmxCentaurSohString\n",
                 reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
