/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef NMXCENTAURSCALARS_H
#define NMXCENTAURSCALARS_H

/*
 * function declarations 
 */
void            init_nmxCentaurScalars(void);
Netsnmp_Node_Handler handle_nmxCentaurSohInteger;
Netsnmp_Node_Handler handle_netSnmpExampleSleeper;
Netsnmp_Node_Handler handle_netSnmpExampleString;

#endif                          /* NMXCENTAURSCALARS_H */
